"""
Neural Score-to-audio alignment using CNN-based multipitch features.

This module implements an alignment pipeline between audio recordings
and symbolic musical scores using multipitch predictions generated by
a convolutional neural network (CNN).

Overview
--------
Instead of extracting pitch features directly from audio, this pipeline
relies on precomputed multipitch activation maps (stored in `.npz` files),
typically produced by a neural network. These activations are converted
into chroma features and aligned with score-derived features using
multi-resolution Dynamic Time Warping (MrMsDTW).

Main steps
----------
1. Load CNN-based multipitch predictions (72 pitch bins over time)
2. Convert multipitch representation into 12-bin chroma features
3. Generate chroma and onset features from symbolic annotations
4. Estimate and apply optimal chroma shift between audio and score
5. Perform alignment using MrMsDTW (SyncToolbox)
6. Warp annotation timestamps according to the alignment path
7. Reinsert and adjust silence segments based on score structure
8. Export aligned annotations as CSV files

Dependencies
------------
- numpy
- pandas
- librosa
- scipy
- synctoolbox
- (local utilities from `common_variables_functions`)

Data Requirements
-----------------
- Audio files (e.g., `.m4a`)
- Precomputed CNN predictions (`.npz` files with 'prediction' key)
- Unfolded symbolic scores in CSV format
"""
from common_variables_functions import *

import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))

############################################
# Alignment
############################################

def transform_pitch_72_to_chroma_12(pitch_energy_72: np.ndarray) -> np.ndarray:
    """
    Convert a pitch activation map over 72 semitone bins (covering 6 octaves) into a 12-bin chroma representation.

    Args:
        - pitch_energy_72 : Array of shape (72, n_frames), representing energy or activation 
                                      for each semitone (e.g., from C1 to C7) at each time frame.

    Returns:
        np.ndarray: Array of shape (12, n_frames), representing the chroma (pitch classes modulo octave), 
                    with either binary or weighted values.
    """
    n_frames = pitch_energy_72.shape[1]
    chroma_12 = np.zeros((12, n_frames))

    for i in range(12):
        bins_indices = list(range(i, 72, 12))
        chroma_12[i, :] = np.sum(pitch_energy_72[bins_indices, :], axis=0)
    return chroma_12


def chroma_sequence_to_matrix(midi_chromas_sequence: list[int|None])->np.ndarray:
    """Returns a binary chroma matrix from a chroma sequence

    Args:
        - midi_chromas_sequence: sequence of chroma values(12) and rest(None) according to the score and the performance

    Returns:
        binary chroma matrix of shape (12, N) where N can be the length of the midi_chromas_sequence
    """
    chroma_matrix = np.zeros((12, len(midi_chromas_sequence)))
    for t, pitch_class in enumerate(midi_chromas_sequence):
        if pitch_class is not None and 0 <= pitch_class < 12:
            chroma_matrix[pitch_class, t] = 1
    return chroma_matrix


def get_predicted_multipitch(predict_filename: str)->np.ndarray:
    """Returns predicted multi-pitch array from a npz file 
       with binary values (or not)

    Args:
        - predict_filename: npz filename

    Returns:
        Predicted multi-pitch with filtered values according to the threshold.
        Shape is (72, timeFrames)
    """
    data = np.load(predict_filename)
    prediction = data['prediction']
    return prediction


def notes_to_midi_pitches(pitches: list[str])->list[int]:
    """Converts a sequence of pitch names and rests into a sequence of MIDI note numbers

    Args:
        - pitches: sequence of pitches names and rests(None) according to the score and the performance

    Returns:
        Sequence of MIDI note numbers (-1 for rest)
    """
    res=[]
    for p in pitches:
        if p == '0':
            res.append(-1)
        else:
            res.append(librosa.note_to_midi(p))    
    return res


def get_features_from_cnn(performer, fantasia):
    predict_filename = f'{NPZ}{performer}/{performer}_f{fantasia}.npz'
    prediction = get_predicted_multipitch(predict_filename)
    chroma_likelihood_matrix= transform_pitch_72_to_chroma_12(prediction)
    f_chroma_quantized = quantize_chroma(f_chroma=chroma_likelihood_matrix)
    return f_chroma_quantized


def main(performer: str, fantasia: int):
    """Main function to use prediction files from MPE and produce and alignment

    Args:
        - performer: name of the performer
        - fantasia: fantasia number (1-12)
    """
    feature_rate = SR/HOP_LENGTH
    step_weights = np.array([1.5, 1.5, 2.0])
    threshold_rec = 10 ** 6
    
    # loading the recording
    ext='.m4a'
    
    audiopath= f'{AUDIOS}{performer}/{performer}_{fantasia}{ext}'
    audio, sr = librosa.load(audiopath, sr=SR)
    
    df_annotation, df_rests, rest_indexes_list = produce_df_from_unfolded_scores(performer, fantasia)
    initial_onset = detect_initial_onset(audio, SR)
    
    df_annotation['start'] += initial_onset
    df_annotation['end'] = df_annotation['start'] + df_annotation['duration']
    
    f_chroma_quantized_annotation, _ = get_features_from_annotation(df_annotation, feature_rate)
    
    f_chroma_quantized_audio = get_features_from_cnn(performer, fantasia)
    
    # Finding optimal shift of chroma vectors
    f_cens_1hz_audio = quantized_chroma_to_CENS(f_chroma_quantized_audio, 201, 50, feature_rate)[0]
    f_cens_1hz_annotation = quantized_chroma_to_CENS(f_chroma_quantized_annotation, 201, 50, feature_rate)[0]
    opt_chroma_shift = compute_optimal_chroma_shift(f_cens_1hz_audio, f_cens_1hz_annotation)
    f_chroma_quantized_annotation = shift_chroma_vectors(f_chroma_quantized_annotation, opt_chroma_shift)
    
    
    wp = sync_via_mrmsdtw(f_chroma1=f_chroma_quantized_audio,
                            f_chroma2=f_chroma_quantized_annotation, 
                            input_feature_rate=feature_rate, 
                            step_weights=step_weights, 
                            threshold_rec=threshold_rec, 
                            verbose=False)
    
    wp = make_path_strictly_monotonic(wp)
    
    df_annotation_warped = df_annotation.copy(deep=True)
    df_annotation_warped["end"] = df_annotation_warped["start"] + df_annotation_warped["duration"]
    df_annotation_warped[['start', 'end']] = scipy.interpolate.interp1d(wp[1] / feature_rate, 
                            wp[0] / feature_rate, kind='linear', fill_value="extrapolate")(df_annotation[['start', 'end']])
    df_annotation_warped["duration"] = df_annotation_warped["end"] - df_annotation_warped["start"]
    df_annotation_warped.drop(columns=['velocity', 'pitch', 'instrument'], inplace=True)
    df_annotation_warped = df_annotation_warped.rename(columns={
                    'start': 'Onset (ms)',
                    'end': 'Offset (ms)',
                    'duration': 'Time_duration (ms)'
                    })
    cols_to_multiply = ['Onset (ms)', 'Offset (ms)', 'Time_duration (ms)']
    df_annotation_warped [cols_to_multiply] = df_annotation_warped [cols_to_multiply] * 1000
    
    # Add df_rests keeping original indexes
    df_annotation_warped = df_annotation_warped.copy()
    df_rests = df_rests.copy()
    df_annotation_warped['Note'] = df_annotation_warped.get('Note', None)
    df_rests['Note'] = '0'
    df_all = pd.concat([df_annotation_warped, df_rests])
    df_all = df_all.sort_index().reset_index(drop=True)
    required_cols = ['Onset (ms)', 'Offset (ms)', 'Score_duration', 'Note']
    missing = [c for c in required_cols if c not in df_all.columns]
    if missing:
        raise ValueError(f"Missing columns: {missing}")
    df_all = adjust_silences(df_all)
    
    col = ['Note','Onset (ms)','Score_duration',
                    'Time-Signature','Movement','Measure','Repeated']

    df_all = df_all[[c for c in col if c in df_all.columns]]
       
    # Save output alignment
    
    output_dir = f"{ALIGNMENTS_NEURAL}{performer}"
    os.makedirs(output_dir, exist_ok=True)
    df_all.to_csv(f"{output_dir}/neural_f{fantasia}.csv", index=False)
   
    
if __name__ == '__main__':
    for performer in ALL:
        for fantasia in range(1, 13):
            main(performer, fantasia)